name: Release
on: 
  release:
    types: [published]
  workflow_dispatch:          
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.1
        with:
          files: COMPONENT/Build4D.4dbase/Contents/
          dest: COMPONENT/Build4D.zip
  publish:
    name: Publish
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    permissions:
      contents: write # for asset upload
    steps:
      - name: Upload
        run: |
          gh release upload ${{github.event.release.tag_name}} ${{ github.workspace }}/COMPONENT/Build4D.zip
